# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Docker container (Alpine Linux)

on:
- push

jobs:
  ssh-pem:
    name: Connect to github.com (PEM format)
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
        container:
        - alpine:3.10
        - alpine:3.11
        - alpine:3.12
        - alpine:3.13
      fail-fast: false
    steps:
    - name: Install packages
      run: apk add openssh-client git
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: unnecessary
    - name: print created files
      run: ls -l /root/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:shimataro/ssh-key-action.git tmp
  ssh-pem-bitbucket:
    name: Connect to bitbucket.org (PEM format)
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
        container:
        - alpine:3.10
        - alpine:3.11
        - alpine:3.12
        - alpine:3.13
      fail-fast: false
    steps:
    - name: Install packages
      run: apk add openssh-client git
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: |
          bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
    - name: print created files
      run: ls -l /root/.ssh
    - name: git clone through SSH
      run: git clone git@bitbucket.org:shimataro999/ssh-test.git tmp
  ssh-pkcs8:
    name: Connect to github.com (PKCS8 format)
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
        container:
        - alpine:3.10
        - alpine:3.11
        - alpine:3.12
        - alpine:3.13
      fail-fast: false
    steps:
    - name: Install packages
      run: apk add openssh-client git
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_PKCS8 }}
        known_hosts: unnecessary
    - name: print created files
      run: ls -l /root/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:shimataro/ssh-key-action.git tmp
  ssh-pkcs8-bitbucket:
    name: Connect to bitbucket.org (PKCS8 format)
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
        container:
        - alpine:3.10
        - alpine:3.11
        - alpine:3.12
        - alpine:3.13
      fail-fast: false
    steps:
    - name: Install packages
      run: apk add openssh-client git
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_PKCS8 }}
        known_hosts: |
          bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
    - name: print created files
      run: ls -l /root/.ssh
    - name: git clone through SSH
      run: git clone git@bitbucket.org:shimataro999/ssh-test.git tmp
  ssh-rfc4716:
    name: Connect to github.com (RFC4716 format)
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
        container:
        - alpine:3.10
        - alpine:3.11
        - alpine:3.12
        - alpine:3.13
      fail-fast: false
    steps:
    - name: Install packages
      run: apk add openssh-client git
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_RFC4716 }}
        known_hosts: unnecessary
    - name: print created files
      run: ls -l /root/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:shimataro/ssh-key-action.git tmp
  ssh-rfc4716-bitbucket:
    name: Connect to bitbucket.org (RFC4716 format)
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
        container:
        - alpine:3.10
        - alpine:3.11
        - alpine:3.12
        - alpine:3.13
      fail-fast: false
    steps:
    - name: Install packages
      run: apk add openssh-client git
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_RFC4716 }}
        known_hosts: |
          bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
    - name: print created files
      run: ls -l /root/.ssh
    - name: git clone through SSH
      run: git clone git@bitbucket.org:shimataro999/ssh-test.git tmp

  key_if_exists_replace-key_exists:
    name: if_key_exists=replace / key exists
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
        container:
        - alpine:3.10
        - alpine:3.11
        - alpine:3.12
        - alpine:3.13
    steps:
    - name: Install packages
      run: apk add openssh-client git
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key (dummy)
      uses: ./.
      with:
        key: "dummy" # replaced
        known_hosts: unnecessary
    - name: Install SSH key (replace)
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: unnecessary
        if_key_exists: replace
    - name: print created files
      run: ls -l /root/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:shimataro/ssh-key-action.git tmp
  key_if_exists_replace-key_doesnt_exist:
    name: if_key_exists=replace / key doesn't exist
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
        container:
        - alpine:3.10
        - alpine:3.11
        - alpine:3.12
        - alpine:3.13
    steps:
    - name: Install packages
      run: apk add openssh-client git
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key (replace)
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: unnecessary
        if_key_exists: replace
    - name: print created files
      run: ls -l /root/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:shimataro/ssh-key-action.git tmp

  key_if_exists_ignore-key_exists:
    name: if_key_exists=ignore / key exists
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
        container:
        - alpine:3.10
        - alpine:3.11
        - alpine:3.12
        - alpine:3.13
    steps:
    - name: Install packages
      run: apk add openssh-client git
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key (dummy)
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: unnecessary
    - name: Install SSH key (replace)
      uses: ./.
      with:
        key: "dummy" # ignored
        known_hosts: unnecessary
        if_key_exists: ignore
    - name: print created files
      run: ls -l /root/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:shimataro/ssh-key-action.git tmp
  key_if_exists_ignore-key_doesnt_exist:
    name: if_key_exists=ignore / key doesn't exist
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
        container:
        - alpine:3.10
        - alpine:3.11
        - alpine:3.12
        - alpine:3.13
    steps:
    - name: Install packages
      run: apk add openssh-client git
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key (replace)
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: unnecessary
        if_key_exists: ignore
    - name: print created files
      run: ls -l /root/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:shimataro/ssh-key-action.git tmp

  key_if_exists_fail-key_exists:
    name: if_key_exists=fail / key exists
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
        container:
        - alpine:3.10
        - alpine:3.11
        - alpine:3.12
        - alpine:3.13
    steps:
    - name: Install packages
      run: apk add openssh-client git
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key (dummy)
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: unnecessary
    - name: Install SSH key (replace)
      uses: ./.
      with:
        key: "dummy" # ignored
        known_hosts: unnecessary
        if_key_exists: fail
      continue-on-error: true
    - name: print created files
      run: ls -l /root/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:shimataro/ssh-key-action.git tmp
  key_if_exists_fail-key_doesnt_exist:
    name: if_key_exists=fail / key doesn't exist
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
        container:
        - alpine:3.10
        - alpine:3.11
        - alpine:3.12
        - alpine:3.13
    steps:
    - name: Install packages
      run: apk add openssh-client git
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key (replace)
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: unnecessary
        if_key_exists: fail
    - name: print created files
      run: ls -l /root/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:shimataro/ssh-key-action.git tmp
