# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Ubuntu 16.04

on:
- push

jobs:
  ssh-pem:
    name: Connect to github.com (PEM format)
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: print created files
      run: ls -l ~/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:shimataro/ssh-key-action.git tmp
  ssh-pkcs8:
    name: Connect to github.com (PKCS8 format)
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_PKCS8 }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: print created files
      run: ls -l ~/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:shimataro/ssh-key-action.git tmp
  ssh-rfc4716:
    name: Connect to github.com (RFC4716 format)
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_RFC4716 }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: print created files
      run: ls -l ~/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:shimataro/ssh-key-action.git tmp
  ssh-with-name:
    name: Connect to github.com with name and config
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        name: ssh_key_name # optional
        config: | # optional
          Host github
            Hostname github.com
            User git
            IdentityFile ~/.ssh/ssh_key_name
    - name: print created files
      run: ls -l ~/.ssh
    - name: git clone through SSH
      run: git clone github:shimataro/ssh-key-action.git tmp
  replace_key_if_exists:
    name: Replace key if exists
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key (dummy)
      uses: ./.
      with:
        key: "dummy"
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Install SSH key (replace)
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: replace
    - name: print created files
      run: ls -l ~/.ssh
    - name: git clone through SSH
      run: git clone github:shimataro/ssh-key-action.git tmp
  replace_key_if_exists_created:
    name: Create key if not exist (if_key_exists=replace)
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key (replace)
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: replace
    - name: print created files
      run: ls -l ~/.ssh
    - name: git clone through SSH
      run: git clone github:shimataro/ssh-key-action.git tmp
